[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build.environment]
  NODE_VERSION = "22"
[build]
  command = "npm run build"
  publish = "dist/browser"
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"